services:
  postgres:
    image: postgres:16
    container_name: empire-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: empire
      POSTGRES_PASSWORD: empirepass
      POSTGRES_DB: empire

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
