BEGIN;

ALTER TABLE city_buildings
ADD COLUMN IF NOT EXISTS stored_resource NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE city_buildings
ADD COLUMN IF NOT EXISTS last_collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMIT;
